export const termsContent = `TERMS AND CONDITIONS

Last Updated: December 17, 2025

1. INTRODUCTION AND ACCEPTANCE These Terms and Conditions ("Terms") constitute a binding legal agreement between you ("User," "you," or "your") and WeaveItAgent ("WeaveIt," "we," "us," or "our").

By accessing the WeaveIt platform, connecting your Solana wallet, holding or transacting with the $WEAV token, or using our AI-driven educational tools (collectively, the "Services"), you agree to be bound by these Terms.

IF YOU DO NOT AGREE TO THESE TERMS, DO NOT USE THE SERVICE.

2. DESCRIPTION OF SERVICE WeaveIt is a decentralized, intelligent, multimodal platform that transforms technical documentation, code repositories, and text into dynamic video tutorials, audio explainers, and interactive learning content using Artificial Intelligence. The Service operates on a "pay-per-prompt" model and subscription tiers.

3. WALLET CONNECTION AND ACCESS

3.1. Wallet Requirement: Access to core features requires connecting a compatible third-party cryptocurrency wallet (e.g., Phantom, Solflare) on the Solana blockchain.

3.2. Security: You are solely responsible for maintaining the security of your wallet and private keys. WeaveIt has no access to your private keys, cannot initiate transactions without your signature, and cannot recover your funds if you lose access to your wallet.

3.3. Eligibility: You must be at least 18 years old to use the Service. By using the Service, you represent and warrant that you meet this age requirement.

4. ARTIFICIAL INTELLIGENCE DISCLAIMER

4.1. Accuracy Warning: The Services utilize Generative AI (Large Language Models) to create content. You acknowledge that AI systems are subject to "hallucinations" and may produce inaccurate, outdated, or incorrect code, explanations, or summaries.

4.2. No Professional Advice: WeaveIt is an educational aid, not a substitute for professional engineering or legal advice. You agree to independently verify all code and technical instructions before deploying them in a live or production environment.

4.3. Liability Waiver: WeaveIt is not liable for any bugs, security vulnerabilities, system failures, or data loss resulting from your use of code or tutorials generated by our platform.

5. USER CONTENT AND INTELLECTUAL PROPERTY

5.1. Your Input: You retain ownership of the code, documentation, PDFs, and URLs you upload or input into WeaveIt ("User Input").

5.2. License to WeaveIt: By uploading User Input, you grant WeaveIt a worldwide, non-exclusive, royalty-free license to process, analyze, and adapt your content solely for the purpose of generating the requested educational output.

5.3. Ownership of Output: Subject to your compliance with these Terms, WeaveIt assigns to you all rights, title, and interest in the specific video, audio, and text outputs generated by the Service for your input ("Output").

5.4. Platform IP: The underlying software, AI models, "Knowledge Workspace," algorithms, and the WeaveIt brand remain the exclusive property of WeaveItAgent.

6. PAYMENTS AND REFUND POLICY

6.1. Payment Methods: Services are paid via fiat currency or $WEAV tokens.

6.2. No Refunds: Due to the irreversible computational costs associated with Generative AI and blockchain transactions, all sales are final. We generally do not offer refunds for "pay-per-prompt" generations or subscriptions, regardless of your satisfaction with the AI output.

6.3. Pricing Changes: We reserve the right to modify pricing (in fiat or $WEAV) at any time.

7. VOICE CLONING AND ETHICAL USE

7.1. Authorization: You may only use the voice cloning feature to clone your own voice or the voice of a person who has given you explicit, written consent.

7.2. Strict Prohibitions: You are strictly prohibited from using the Service to:

Clone the voices of politicians, celebrities, or public figures without their consent.

Create "deepfakes" intended to deceive, defraud, or mislead others.

Generate hate speech, harassment, defamatory content, or content that promotes violence.

7.3. Enforcement: Violation of this section will result in an immediate permanent ban from the platform and the blacklisting of your wallet address. We reserve the right to report illegal use to relevant authorities.

8. $WEAV TOKENOMICS AND RISKS

8.1. Utility Token Only: The $WEAV token is strictly a utility token designed to access compute power and features within the WeaveIt ecosystem. It is not a security, stock, or investment contract.

8.2. No Expectation of Profit: You agree that you are not purchasing $WEAV with the expectation of profit derived from the efforts of WeaveItAgent or any third party.

8.3. Volatility: Crypto assets are highly volatile. You assume all risks associated with the purchase, holding, and use of $WEAV. WeaveItAgent is not responsible for any financial loss due to token price fluctuations or smart contract exploits.

9. PROHIBITED ACTIVITIES You agree not to:

Reverse engineer, decompile, or disassemble the WeaveIt platform.

Use the Service to generate malicious code (malware, viruses, exploits).

Upload content that infringes on the Intellectual Property rights of others.

Interfere with or disrupt the integrity or performance of the Service.

10. LIMITATION OF LIABILITY TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, WEAVEITAGENT SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUE, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (A) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE; (B) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICE; OR (C) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT.

11. DISPUTE RESOLUTION AND ARBITRATION

11.1. Binding Arbitration: In the event of any dispute, claim, or controversy arising out of or relating to these Terms, the parties agree to resolve the matter through binding arbitration, rather than in court. The arbitration shall be conducted by a neutral arbitrator agreed upon by both parties.

11.2. Waiver of Class Actions: You agree to resolve disputes only on an individual basis. You waive the right to bring a class action, class arbitration, or representative action against WeaveItAgent.

11.3. Global Enforcement: The parties agree that this arbitration clause is intended to be enforceable globally, and judgment on the arbitration award may be entered in any court having jurisdiction thereof.

12. MODIFICATIONS WeaveItAgent reserves the right to modify these Terms at any time. We will provide notice of material changes via the platform or official community channels. Your continued use of the Service after such changes constitutes your acceptance of the new Terms.`

export const privacyContent = `WEAVEIT AGENT PRIVACY POLICY
Last Updated: December 17, 2025

1. INTRODUCTION WeaveItAgent ("WeaveIt," "we," "us," or "our") respects your privacy and is committed to protecting the personal and technical data you share with us. This Privacy Policy explains how we collect, use, and safeguard your information when you access our platform, connect your Solana wallet, or use our AI-driven educational services (the "Services").
2. INFORMATION WE COLLECT: We collect information in four categories:
   A. Personal Information: If you create an account or subscribe, we may collect your name, email address, and username.
   B. Blockchain & Wallet Data: When you connect a wallet (e.g., Phantom, Solflare), we collect your public wallet address and transaction history related to the $WEAV token. We do not have access to your private keys or seed phrases.
   C. AI Input Data: This includes the code repositories, technical documentation, PDFs, and URLs you upload for analysis, as well as the text prompts you enter.
   D. Biometric & Voice Data: If you use our voice cloning features, we collect the voice samples you upload. This is considered sensitive biometric data.
3. HOW WE USE YOUR INFORMATION: We use your data strictly to provide and improve the Service:
   Service Delivery: To generate the video tutorials, summaries, and quizzes you request.
   AI Processing: Your code and voice samples are processed by our AI models solely to generate the specific output you requested.
   Transaction Verification: To confirm your $WEAV token balance or process "pay-per-prompt" payments on the Solana blockchain.
   Safety & Compliance: To detect and prevent deepfakes, fraud, or the generation of malicious content.
4. SHARING OF INFORMATION: We do not sell your personal data. However, we must share data with specific infrastructure providers to function:
   Third-Party AI Providers: We transmit your input text and voice samples to third-party AI model providers (e.g., OpenAI, ElevenLabs, Anthropic) for processing. These providers are contractually limited to using your data for generation purposes only.
   Blockchain Public Ledger: Please be aware that your wallet address and transaction details are permanently recorded on the public Solana blockchain. We cannot delete or hide this information.
   Service Providers: We use trusted third parties for hosting (e.g., AWS, Vercel) and analytics.

5. DATA RETENTION
   Voice Models: Voice clones are retained only as long as you maintain an active account or until you manually delete them. You may delete a custom voice model at any time via your dashboard.
   Input Code: Codebases uploaded for analysis are processed in ephemeral sessions and are not permanently stored in our database after the session ends, unless you explicitly save the project to your workspace.
   Blockchain Data: On-chain data is immutable and stored permanently by the decentralized network, not by us.
6. YOUR RIGHTS: Depending on your location, you may have the right to:
   Access: Request a copy of the data we hold about you.
   Delete: Request the deletion of your account and off-chain data (email, voice models). Note: We cannot delete data from the blockchain.
   Rectify: Correct inaccurate information.
   To exercise these rights, contact us at: weaveitagent@gmail.com.
7. SECURITY We use industry-standard encryption (TLS/SSL) to protect your data in transit. Voice samples and sensitive inputs are stored using encryption-at-rest. However, no method of transmission over the Internet is 100% secure, and we cannot guarantee absolute security.
8. INTERNATIONAL TRANSFERS: WeaveItAgent operates globally. By using the Service, you acknowledge that your data may be transferred to and processed in servers located in the United States or other jurisdictions where our AI providers operate.
9. COOKIES: We use essential cookies to maintain your session and preferences. We may use analytics cookies to understand how users interact with the platform. You can control cookies through your browser settings.
10. CHANGES TO THIS POLICY: We may update this Privacy Policy from time to time. We will notify you of significant changes via the platform. Your continued use of the Service constitutes acceptance of the updated policy.
11. CONTACT US: If you have questions about this Privacy Policy, please contact us at: weaveitagent@gmail.com.`

export const cookieContent = `Cookie Policy

We use cookies to enhance your experience on our platform. Essential cookies are required for the site to function, while analytics cookies help us improve our services. You can manage your cookie preferences in your browser settings.`